image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addBadge: true
    addLabel: ready-to-code
tasks:
  - init: cargo build
    command: cargo run --example example1